const a =10;

try{
    a= 5;
}catch(e){
    console.log('Ocorreu um erro: ' + e);
}

